### ISSUE TITLE
Exception when entering dummy info

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#105]
Configuration Name: test
Enabled?: No
SP Issuer URL: test
Any metadata file

```
ERROR servlet.ReloadableServletContainer: Unhandled error during request processing: 
javax.servlet.ServletException: com.dotcms.repackage.org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: com.dotcms.repackage.org.jvnet.mimepull.MIMEMessage.close()V
	at com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:487) ~[dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:425) ~[dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:383) ~[dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:336) ~[dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:223) ~[dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.rest.servlet.ReloadableServletContainer.service(ReloadableServletContainer.java:105) [dotcms_4.3.2_ae725e9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CMSFilter.doFilter(CMSFilter.java:203) [dotcms_4.3.2_ae725e9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.3.2_ae725e9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.filters.interceptor.AbstractWebInterceptorSupportFilter.doFilter(AbstractWebInterceptorSupportFilter.java:73) [dotcms_4.3.2_ae725e9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.cms.urlmap.filters.URLMapFilter.doFilter(URLMapFilter.java:325) [dotcms_4.3.2_ae725e9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.VanityURLFilter.doFilter(VanityURLFilter.java:110) [dotcms_4.3.2_ae725e9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.repackage.org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:404) [dot.urlrewritefilter-4.0.3_2.jar:4.0.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.TimeMachineFilter.doFilter(TimeMachineFilter.java:132) [dotcms_4.3.2_ae725e9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.ThreadNameFilter.doFilter(ThreadNameFilter.java:90) [dotcms_4.3.2_ae725e9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CookiesFilter.doFilter(CookiesFilter.java:38) [dotcms_4.3.2_ae725e9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotmarketing.filters.CharsetEncodingFilter.doFilter(CharsetEncodingFilter.java:108) [dotcms_4.3.2_ae725e9.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:177) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: com.dotcms.repackage.org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: com.dotcms.repackage.org.jvnet.mimepull.MIMEMessage.close()V
	at com.dotcms.repackage.org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:278) ~[dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:260) ~[dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:509) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) ~[dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	... 60 more
Caused by: java.lang.NoSuchMethodError: com.dotcms.repackage.org.jvnet.mimepull.MIMEMessage.close()V
	at com.dotcms.repackage.org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.getMimeParts(MultiPartReaderClientSide.java:276) ~[dot.jersey-media-multipart-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readMultiPart(MultiPartReaderClientSide.java:231) ~[dot.jersey-media-multipart-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.media.multipart.internal.MultiPartReaderServerSide.readMultiPart(MultiPartReaderServerSide.java:91) ~[dot.jersey-media-multipart-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:183) ~[dot.jersey-media-multipart-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.media.multipart.internal.MultiPartReaderClientSide.readFrom(MultiPartReaderClientSide.java:93) ~[dot.jersey-media-multipart-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:74) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:234) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.media.multipart.internal.FormDataParamValueFactoryProvider$ValueFactory.getEntity(FormDataParamValueFactoryProvider.java:134) ~[dot.jersey-media-multipart-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.media.multipart.internal.FormDataParamValueFactoryProvider$FormDataParamValueFactory.provide(FormDataParamValueFactoryProvider.java:288) ~[dot.jersey-media-multipart-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.provide(ParamValueFactoryWithSource.java:71) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:90) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:127) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:315) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:297) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.internal.Errors.process(Errors.java:267) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) ~[dot.jersey-common-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) ~[dot.jersey-server-2.22.1_1.jar:?]
	at com.dotcms.repackage.org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471) ~[dot.jersey-container-servlet-core-2.22.1_1.jar:?]
	... 60 more
```

**Comment by gabbydotCMS** [comment]
Not happening on latest code merged onto V4/dotCMS 4.3.x master branch.

**Comment by gabbydotCMS** [comment]
I was able to reproduce this one again even when adding key and certificate files.

**Comment by gabbydotCMS** [comment]
Happening only from IE.

These are the messages in the browser's console:

```
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (menu, line 0)
[Error] ERROR
e
	_ (vendor.c093a9a1e181d61ae3da.bundle.js:1:28175)
	handleError (vendor.c093a9a1e181d61ae3da.bundle.js:1:87081)
	next (vendor.c093a9a1e181d61ae3da.bundle.js:1:106662)
	(anonymous function) (vendor.c093a9a1e181d61ae3da.bundle.js:1:101177)
	__tryOrUnsub (vendor.c093a9a1e181d61ae3da.bundle.js:1:1873313)
	next (vendor.c093a9a1e181d61ae3da.bundle.js:1:1872599)
	_next (vendor.c093a9a1e181d61ae3da.bundle.js:1:1871645)
	next (vendor.c093a9a1e181d61ae3da.bundle.js:1:1871317)
	next (vendor.c093a9a1e181d61ae3da.bundle.js:1:3456963)
	emit (vendor.c093a9a1e181d61ae3da.bundle.js:1:100951)
	run (polyfills.57119eda053c5d8c3d49.bundle.js:1:55224)
	onHandleError (vendor.c093a9a1e181d61ae3da.bundle.js:1:33225)
	runTask (polyfills.57119eda053c5d8c3d49.bundle.js:1:55974)
	invokeTask (polyfills.57119eda053c5d8c3d49.bundle.js:1:61874)
	h (polyfills.57119eda053c5d8c3d49.bundle.js:1:41566)
	v (polyfills.57119eda053c5d8c3d49.bundle.js:1:41779)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (dotcms.css.map, line 0)
> Selected Element
< <div class="dijitDialogUnderlay _underlay" data-dojo-attach-point="node" id="addEditIdPDialog_underlay" style="width: 1490px; height: 652px;"></div>
[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (idp, line 0)
```

![screen shot 2018-07-30 at 5 09 31 pm](https://user-images.githubusercontent.com/1569509/43423807-613decbc-941b-11e8-8c1f-305f0ada448c.png)
