### ISSUE TITLE
Simplify handling of empty mandatory attributes from IdP

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#37]
Alternative way to implement ToleranceOpenSamlAuthenticationServiceImpl to handle empty first-name, last-name, and email address.

When default, dummy values for these fields are not set, we need to be able to report back to the user why their accounts could not be created/authenticated (better error handling when mandatory fields are absent).

**Comment by chrismccracken** [comment]
Update first, last, email dotCMS attributes from IDP on login success.

**Comment by chrismccracken** [comment]
Config:
```attribute.email.name=mail
attribute.firstname.name=givenName
attribute.firstname.nullvalue=
attribute.lastlame.name=sn
attribute.lastlame.nullvalue=```

**Comment by chrismccracken** [comment]
if null email from idp, use this strategy to autogenerate value:
$subname = $idp.attributes.nameid, substitute `_at_` for `@`
email replacement value = `no-reply+$subname@no-reply.dotcms.com`

**Comment by jdotcms** [comment]
Roles has been changed from roles.attribute to attribute.roles.name

**Comment by gabbydotCMS** [comment]
Got a invalid error message when having null first name, last name, and email values:

```
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Resolved assertion: org.opensaml.saml.saml2.core.impl.AssertionImpl@551105a3
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Resolving attributes - Name ID : gabriela@dotcms.com
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Elements of type AttributeStatement in assertion : 1
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Attribute Statement - local name: AttributeStatement, type: AttributeStatementType, number of attributes: 3
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Attribute - friendly name: null, name: FirstName, type: AttributeType, number of values: 1
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Attribute did not match any user property
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Attribute - friendly name: null, name: LastName, type: AttributeType, number of values: 1
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Attribute did not match any user property
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Attribute - friendly name: null, name: Eamil, type: AttributeType, number of values: 1
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Attribute did not match any user property
[26/10/17 12:13:59:145 EDT] DEBUG v3.OpenSamlAuthenticationServiceImpl: Validating user - AttributesBean{nameID='gabriela@dotcms.com', email='', lastName='', firstName='', addRoles=false, roles=null}
[26/10/17 12:13:59:146 EDT] ERROR v3.OpenSamlAuthenticationServiceImpl: No matching user, creating
[26/10/17 12:13:59:148 EDT] ERROR business.UserFactoryLiferayImpl: Please enter a valid Email Address
com.liferay.portal.UserEmailAddressException: Please enter a valid Email Address
	at com.liferay.portal.ejb.UserLocalManagerImpl.validate(UserLocalManagerImpl.java:574) ~[dotcms_4.2.0_999999.jar:?]
	at com.liferay.portal.ejb.UserLocalManagerImpl.addUser(UserLocalManagerImpl.java:103) ~[dotcms_4.2.0_999999.jar:?]
	at com.liferay.portal.ejb.UserLocalManagerUtil.addUser(UserLocalManagerUtil.java:49) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.business.UserFactoryLiferayImpl.createUser(UserFactoryLiferayImpl.java:111) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.business.UserAPIImpl.createUser_aroundBody12(UserAPIImpl.java:151) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.business.UserAPIImpl$AjcClosure13.run(UserAPIImpl.java:1) ~[dotcms_4.2.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) [dotcms_4.2.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) [dotcms_4.2.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) [dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.business.UserAPIImpl.createUser(UserAPIImpl.java:150) [dotcms_4.2.0_999999.jar:?]
	at com.dotcms.plugin.saml.v3.OpenSamlAuthenticationServiceImpl.createNewUser(OpenSamlAuthenticationServiceImpl.java:684) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.OpenSamlAuthenticationServiceImpl.resolveUser(OpenSamlAuthenticationServiceImpl.java:444) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.OpenSamlAuthenticationServiceImpl.getUser(OpenSamlAuthenticationServiceImpl.java:206) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.autoLogin(SamlAccessFilter.java:596) [SamlAccessFilter.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doAutoLogin(SamlAccessFilter.java:561) [SamlAccessFilter.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:274) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[26/10/17 12:13:59:149 EDT] ERROR v3.OpenSamlAuthenticationServiceImpl: Error creating user:Please enter a valid Email Address
com.dotmarketing.exception.DotDataException: Please enter a valid Email Address
	at com.dotmarketing.business.UserFactoryLiferayImpl.createUser(UserFactoryLiferayImpl.java:120) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.business.UserAPIImpl.createUser_aroundBody12(UserAPIImpl.java:151) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.business.UserAPIImpl$AjcClosure13.run(UserAPIImpl.java:1) ~[dotcms_4.2.0_999999.jar:?]
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149) ~[aspectjrt-1.8.10.jar:?]
	at com.dotcms.aspects.aspectj.AspectJDelegateMethodInvocation.proceed(AspectJDelegateMethodInvocation.java:43) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.db.LocalTransaction.wrapReturnWithListeners(LocalTransaction.java:39) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.aspects.interceptors.WrapInTransactionMethodInterceptor.invoke(WrapInTransactionMethodInterceptor.java:23) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.aspects.aspectj.WrapInTransactionAspect.invoke(WrapInTransactionAspect.java:41) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.business.UserAPIImpl.createUser(UserAPIImpl.java:150) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotcms.plugin.saml.v3.OpenSamlAuthenticationServiceImpl.createNewUser(OpenSamlAuthenticationServiceImpl.java:684) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.OpenSamlAuthenticationServiceImpl.resolveUser(OpenSamlAuthenticationServiceImpl.java:444) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.OpenSamlAuthenticationServiceImpl.getUser(OpenSamlAuthenticationServiceImpl.java:206) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.autoLogin(SamlAccessFilter.java:596) [SamlAccessFilter.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doAutoLogin(SamlAccessFilter.java:561) [SamlAccessFilter.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:274) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: com.liferay.portal.UserEmailAddressException: Please enter a valid Email Address
	at com.liferay.portal.ejb.UserLocalManagerImpl.validate(UserLocalManagerImpl.java:574) ~[dotcms_4.2.0_999999.jar:?]
	at com.liferay.portal.ejb.UserLocalManagerImpl.addUser(UserLocalManagerImpl.java:103) ~[dotcms_4.2.0_999999.jar:?]
	at com.liferay.portal.ejb.UserLocalManagerUtil.addUser(UserLocalManagerUtil.java:49) ~[dotcms_4.2.0_999999.jar:?]
	at com.dotmarketing.business.UserFactoryLiferayImpl.createUser(UserFactoryLiferayImpl.java:111) ~[dotcms_4.2.0_999999.jar:?]
	... 33 more
```

Same thing happened after setting:

attribute.firstname.nullvalue=MyFirstName
attribute.lastlame.nullvalue=MyLastName

Please take into account that the IdP was not sending null values; it was just that the names used by the IdP for those attributes didn't match our default names. However, we should not be receiving an invalid email error from liferay since we should at least be sending a fake email to dotCMS.

**Comment by gabbydotCMS** [comment]
From our conversation today:

Case 1: Null value sent by the IdP for name, first name, and/or email address
   - An INFO message will be logged to indicate the attribute whose value was null
   - If first name == null and attribute.firstname.nullvalue is defined, attribute.firstname.nullvalue will be used as first name
   - If last name == null and attribute.lastlame.name is defined, attribute.lastlame.name will be used as last name
  - If email == null, $subname = $idp.attributes.nameid, substitute _at_ for @
email replacement value = no-reply+$subname@no-reply.dotcms.com

Case 2: No attributes matching attribute.email.name, attribute.firstname.name, and/or attribute.lastlame.name
   - A WARNING message will be logged indicating the name of the attribute that could not be found in the assertion
   - Same logic than in Case 1 to create fake values

**Comment by jdotcms** [comment]
The commit 6b8b041e432b5a2dbff645918caa0583c7cf66fd reflect these requirements

**Comment by jdotcms** [comment]
We have to apply the following logic for the default email:
```
if ($email == null && attribute.email.allownull == false) {
  log ERROR and use default 401 handler
} else if ($email == null && attribute.email.allownull == true} {
  use email autofill strategy
}
```

**Comment by jdotcms** [comment]
Last requirement covered by: 1ce2df6ca24ea0c1906f382aa676525ba16a8220
