### ISSUE TITLE
org.opensaml.xml.signature.impl.CryptoBinaryBuilder cannot be cast to org.opensaml.core.xml.XMLObjectBuilder

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/plugin-com.dotcms.dotsaml#58]
SAML fails to init on startup, causes SAML filter to throw 500 for all requests.

This looks like a conflict between `opensaml-core-3.2.0.jar` and `opensaml-xmltooling-1.4.6.jar` that varies based on classpath resolution.

See https://github.com/pac4j/pac4j/issues/353, likely fallout from the openSAML2 -> opemSAML3 upgrade.

```
[26/10/17 09:51:56:342 CDT] ERROR filter.SamlAccessFilter: SAML ERROR: org.opensaml.xml.signature.impl.CryptoBinaryBuilder cannot be cast to org.opensaml.core.xml.XMLObjectBuilder
java.lang.ClassCastException: org.opensaml.xml.signature.impl.CryptoBinaryBuilder cannot be cast to org.opensaml.core.xml.XMLObjectBuilder
	at org.opensaml.core.xml.config.XMLConfigurator.initializeObjectProviders(XMLConfigurator.java:238) ~[opensaml-core-3.2.0.jar:?]
	at org.opensaml.core.xml.config.XMLConfigurator.load(XMLConfigurator.java:203) ~[opensaml-core-3.2.0.jar:?]
	at org.opensaml.core.xml.config.XMLConfigurator.load(XMLConfigurator.java:188) ~[opensaml-core-3.2.0.jar:?]
	at org.opensaml.core.xml.config.XMLConfigurator.load(XMLConfigurator.java:162) ~[opensaml-core-3.2.0.jar:?]
	at org.opensaml.core.xml.config.AbstractXMLObjectProviderInitializer.init(AbstractXMLObjectProviderInitializer.java:52) ~[opensaml-core-3.2.0.jar:?]
	at org.opensaml.core.config.InitializationService.initialize(InitializationService.java:56) ~[opensaml-core-3.2.0.jar:?]
	at com.dotcms.plugin.saml.v3.init.DefaultInitializer.initService(DefaultInitializer.java:167) ~[DefaultInitializer.class:?]
	at com.dotcms.plugin.saml.v3.init.DefaultInitializer.init(DefaultInitializer.java:72) ~[DefaultInitializer.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.init(SamlAccessFilter.java:140) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterConfig.initFilter(ApplicationFilterConfig.java:279) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterConfig.getFilter(ApplicationFilterConfig.java:260) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterConfig.<init>(ApplicationFilterConfig.java:105) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.filterStart(StandardContext.java:4565) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5180) [catalina.jar:8.0.18]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1069) [catalina.jar:8.0.18]
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1719) [catalina.jar:8.0.18]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_141]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_141]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_141]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_141]

**Comment by chrismccracken** [comment]
Fixed in 3.7 branch
