### ISSUE TITLE
Exception when installing the plugin on the second node of the cluster

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#62]
[15/11/17 20:42:42:447 EST] ERROR util.InstancePool: com.dotcms.plugin.saml.v3.config.SiteConfigurationService
java.lang.InstantiationException: com.dotcms.plugin.saml.v3.config.SiteConfigurationService
	at java.lang.Class.newInstance(Class.java:427) ~[?:1.8.0_121]
	at com.liferay.util.InstancePool._get(InstancePool.java:69) [dotcms_3.7.1_8d1e90a.jar:?]
	at com.liferay.util.InstancePool.get(InstancePool.java:39) [dotcms_3.7.1_8d1e90a.jar:?]
	at com.dotcms.plugin.saml.v3.SiteConfigurationResolver.resolveConfiguration(SiteConfigurationResolver.java:39) [SiteConfigurationResolver.class:?]
	at com.dotcms.plugin.saml.v3.SiteConfigurationResolver.resolveConfiguration(SiteConfigurationResolver.java:26) [SiteConfigurationResolver.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:296) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:673) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodException: com.dotcms.plugin.saml.v3.config.SiteConfigurationService.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082) ~[?:1.8.0_121]
	at java.lang.Class.newInstance(Class.java:412) ~[?:1.8.0_121]
	... 25 more

**Comment by jdotcms** [comment]
PR: https://github.com/dotCMS/plugin-com.dotcms.dotsaml/pull/64/files
