### ISSUE TITLE
REQ#1 - ERROR - 500 error when trying to log into the backend

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#88]
This is the error shown in dotcms-saml.log:

```
[27/04/18 09:58:41:400 EDT] ERROR meta.DefaultMetaDescriptorServiceImpl: null
java.lang.NullPointerException
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.unmarshall(DefaultMetaDescriptorServiceImpl.java:448) [DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.parse(DefaultMetaDescriptorServiceImpl.java:87) [DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getMetaData(MetaDataHelper.java:39) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getIdentityProviderDestinationSSOURL(MetaDataHelper.java:81) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.getIPDSSODestination(SamlUtils.java:266) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.buildAuthnRequest(SamlUtils.java:224) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.service.OpenSamlAuthenticationServiceImpl.authentication(OpenSamlAuthenticationServiceImpl.java:222) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:137) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[27/04/18 09:58:41:400 EDT] ERROR config.MetaDataHelper: null
com.dotcms.plugin.saml.v3.exception.DotSamlException
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.unmarshall(DefaultMetaDescriptorServiceImpl.java:453) ~[DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.parse(DefaultMetaDescriptorServiceImpl.java:87) ~[DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getMetaData(MetaDataHelper.java:39) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getIdentityProviderDestinationSSOURL(MetaDataHelper.java:81) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.getIPDSSODestination(SamlUtils.java:266) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.buildAuthnRequest(SamlUtils.java:224) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.service.OpenSamlAuthenticationServiceImpl.authentication(OpenSamlAuthenticationServiceImpl.java:222) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:137) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.unmarshall(DefaultMetaDescriptorServiceImpl.java:448) ~[DefaultMetaDescriptorServiceImpl.class:?]
	... 26 more
```

This is the configuration I have set:

![screen shot 2018-04-27 at 10 05 37 am](https://user-images.githubusercontent.com/1569509/39366683-9d6da686-4a02-11e8-9b5a-0402622fcf07.png)
![screen shot 2018-04-27 at 10 06 26 am](https://user-images.githubusercontent.com/1569509/39366702-ae01e28c-4a02-11e8-9688-f3f5f3537cf7.png)
![screen shot 2018-04-27 at 10 06 58 am](https://user-images.githubusercontent.com/1569509/39366760-d92dfa04-4a02-11e8-9627-a2702d83e482.png)

I'm trying to log into the backend via:

test1.dotsaml.com:8080/c

**Comment by gabbydotCMS** [comment]
@thstave .. same thing:

![screen shot 2018-04-27 at 10 37 33 am](https://user-images.githubusercontent.com/1569509/39368233-0dbd80ce-4a07-11e8-9e1f-5756dbfcd380.png)

```
[27/04/18 10:36:24:439 EDT] ERROR meta.DefaultMetaDescriptorServiceImpl: null
java.lang.NullPointerException
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.unmarshall(DefaultMetaDescriptorServiceImpl.java:448) [DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.parse(DefaultMetaDescriptorServiceImpl.java:87) [DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getMetaData(MetaDataHelper.java:39) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getIdentityProviderDestinationSSOURL(MetaDataHelper.java:81) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.getIPDSSODestination(SamlUtils.java:266) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.buildAuthnRequest(SamlUtils.java:224) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.service.OpenSamlAuthenticationServiceImpl.authentication(OpenSamlAuthenticationServiceImpl.java:222) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:137) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[27/04/18 10:36:24:439 EDT] ERROR config.MetaDataHelper: null
com.dotcms.plugin.saml.v3.exception.DotSamlException
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.unmarshall(DefaultMetaDescriptorServiceImpl.java:453) ~[DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.parse(DefaultMetaDescriptorServiceImpl.java:87) ~[DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getMetaData(MetaDataHelper.java:39) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getIdentityProviderDestinationSSOURL(MetaDataHelper.java:81) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.getIPDSSODestination(SamlUtils.java:266) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.buildAuthnRequest(SamlUtils.java:224) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.service.OpenSamlAuthenticationServiceImpl.authentication(OpenSamlAuthenticationServiceImpl.java:222) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:137) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.unmarshall(DefaultMetaDescriptorServiceImpl.java:448) ~[DefaultMetaDescriptorServiceImpl.class:?]
	... 26 more
```

**Comment by thstave** [comment]
Do you mind letting me know what you have setup in Okta.  I will build a configuration that mirrors yours and see what I get.

**Comment by thstave** [comment]
Sorry.  I should have looked closer at your configuration.  Try this as SP Endpoint Hostname: http://test1.dotsaml.com/dotsaml/login

**Comment by gabbydotCMS** [comment]
Hi @thstave ... Same thing after modifying the SP Endpoint Hostname:

```
[27/04/18 11:54:13:620 EDT] ERROR meta.DefaultMetaDescriptorServiceImpl: null
java.lang.NullPointerException
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.unmarshall(DefaultMetaDescriptorServiceImpl.java:448) [DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.parse(DefaultMetaDescriptorServiceImpl.java:87) [DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getMetaData(MetaDataHelper.java:39) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getIdentityProviderDestinationSSOURL(MetaDataHelper.java:81) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.getIPDSSODestination(SamlUtils.java:266) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.buildAuthnRequest(SamlUtils.java:224) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.service.OpenSamlAuthenticationServiceImpl.authentication(OpenSamlAuthenticationServiceImpl.java:222) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:137) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[27/04/18 11:54:13:620 EDT] ERROR config.MetaDataHelper: null
com.dotcms.plugin.saml.v3.exception.DotSamlException
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.unmarshall(DefaultMetaDescriptorServiceImpl.java:453) ~[DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.parse(DefaultMetaDescriptorServiceImpl.java:87) ~[DefaultMetaDescriptorServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getMetaData(MetaDataHelper.java:39) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.config.MetaDataHelper.getIdentityProviderDestinationSSOURL(MetaDataHelper.java:81) [MetaDataHelper.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.getIPDSSODestination(SamlUtils.java:266) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.util.SamlUtils.buildAuthnRequest(SamlUtils.java:224) [SamlUtils.class:?]
	at com.dotcms.plugin.saml.v3.service.OpenSamlAuthenticationServiceImpl.authentication(OpenSamlAuthenticationServiceImpl.java:222) [OpenSamlAuthenticationServiceImpl.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:137) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.NullPointerException
	at com.dotcms.plugin.saml.v3.meta.DefaultMetaDescriptorServiceImpl.unmarshall(DefaultMetaDescriptorServiceImpl.java:448) ~[DefaultMetaDescriptorServiceImpl.class:?]
	... 26 more
```
![screen shot 2018-04-27 at 11 55 46 am](https://user-images.githubusercontent.com/1569509/39372294-f6ed38a2-4a11-11e8-94db-363025573569.png)

I can share with you the IdP metadata file, private key, and public key I'm using if that helps, but I don't think this is a communication issue with the IdP as by the NPE we are getting here (and also the one reported on #89 ), we are not even generating a SAML request to the IdP (I'll check the messages with the SAML extension on my browser, though).

Can you document one of your successful test cases against Okta and provide me with your IdP metadata so that I can try to reproduce that locally?

Thanks !!

Gabby

**Comment by thstave** [comment]
I'm putting together some samples now.  In the meantime could you please let me know how you set up your "authorizations" field in Okta?
