### ISSUE TITLE
REQ#1 - ERROR - 500 Error when editing a SAML Config

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#89]
I logged into the backend via http://demo.dotcms.com:8080/c

demo.dotcms.com is not associated to any SAML Config.

When trying to edit one of the SAML Configs, I get the following error in dotcms-saml.log:

```
[27/04/18 10:13:33:591 EDT]  INFO config.IdpConfigHelper: Error reading SamlCache
[27/04/18 10:13:33:591 EDT] ERROR cache.SamlCacheImpl: IdpConfig count not set in cache.
java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542) ~[?:1.8.0_162]
	at java.lang.Integer.parseInt(Integer.java:615) ~[?:1.8.0_162]
	at com.dotcms.plugin.saml.v3.cache.SamlCacheImpl.getIdpCount(SamlCacheImpl.java:490) ~[SamlCacheImpl.class:?]
	at com.dotcms.plugin.saml.v3.cache.SamlCacheImpl.incrementIdpCount(SamlCacheImpl.java:472) ~[SamlCacheImpl.class:?]
	at com.dotcms.plugin.saml.v3.cache.SamlCacheImpl.addIdpConfig(SamlCacheImpl.java:133) ~[SamlCacheImpl.class:?]
	at com.dotcms.plugin.saml.v3.cache.SamlCacheImpl.lambda$addIdpConfigs$1(SamlCacheImpl.java:188) ~[SamlCacheImpl.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_162]
	at com.dotcms.plugin.saml.v3.cache.SamlCacheImpl.addIdpConfigs(SamlCacheImpl.java:185) [SamlCacheImpl.class:?]
	at com.dotcms.plugin.saml.v3.config.IdpConfigHelper.getIdpConfigsFileSystem(IdpConfigHelper.java:372) [IdpConfigHelper.class:?]
	at com.dotcms.plugin.saml.v3.config.IdpConfigHelper.findSiteIdpConfigFileSystem(IdpConfigHelper.java:202) [IdpConfigHelper.class:?]
	at com.dotcms.plugin.saml.v3.config.IdpConfigHelper.findSiteIdpConfig(IdpConfigHelper.java:170) [IdpConfigHelper.class:?]
	at com.dotcms.plugin.saml.v3.util.SiteIdpConfigResolver.resolveIdpConfig(SiteIdpConfigResolver.java:118) [SiteIdpConfigResolver.class:?]
	at com.dotcms.plugin.saml.v3.util.SiteIdpConfigResolver.resolveIdpConfig(SiteIdpConfigResolver.java:48) [SiteIdpConfigResolver.class:?]
	at com.dotcms.plugin.saml.v3.filter.SamlAccessFilter.doFilter(SamlAccessFilter.java:82) [SamlAccessFilter.class:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.18]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.18]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.18]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610) [catalina.jar:8.0.18]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.18]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516) [catalina.jar:8.0.18]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659) [tomcat-coyote.jar:8.0.18]
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558) [tomcat-coyote.jar:8.0.18]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515) [tomcat-coyote.jar:8.0.18]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_162]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.18]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
[27/04/18 10:13:33:592 EDT]  INFO filter.SamlAccessFilter: Error reading idpConfig for the site: demo.dotcms.com

```

**Comment by gabbydotCMS** [comment]
Not happening on https://github.com/dotCMS/plugin-com.dotcms.dotsaml/tree/debug20180502-1 .

Fix to be check on code review.
